# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8

definitions:
  steps:
    - step: &flake8-check
        name: Lint code with flake8
        caches:
          - pip
        script:
          - make flake8
    - step: &mypy-check
        name: Lint code with mypy
        caches:
          - pip
        script:
          - make mypy
    - step: &bandit-check
        name: Lint code with bandit
        caches:
          - pip
        script:
          - make bandit
    - step: &test-step
        name: Test with pytest
        caches:
          - pip
        script:
          - make test
    - step: &build-step
        name: Build package
        caches:
          - pip
        script:
          - apt update -y && apt install -y make curl
          - pip install twine
          - make build_whl
          - twine check dist/*.whl
pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *flake8-check
          - step: *mypy-check
          - step: *bandit-check
      - parallel:
          - step:
              image: python:3.6
              <<: *test-step
          - step:
              image: python:3.7
              <<: *test-step
          - step:
              image: python:3.8
              <<: *test-step
      - step:
          image: python:3.8
          <<: *build-step
  branches:
    "{master,develop}":
      - parallel:
          - step: *flake8-check
          - step: *mypy-check
          - step: *bandit-check
      - parallel:
          - step:
              image: python:3.6
              <<: *test-step
          - step:
              image: python:3.7
              <<: *test-step
          - step:
              image: python:3.8
              <<: *test-step
      - step:
          image: python:3.8
          <<: *build-step
  tags:
    "v*":   # release tag
      - step:
          name: Deploy to pypi
          script:
            - pipe: atlassian/pypi-publish:0.3.1
              variables:
                PYPI_USERNAME: $TWINE_USERNAME
                PYPI_PASSWORD: $TWINE_PASSWORD
                DISTRIBUTIONS: 'bdist_wheel'
                REPOSITORY: $TWINE_REPOSITORY_URL