.PHONY: clean help

help:
	clear;
	@echo "================= Usage =================";
	@echo "clean                  : Remove autogenerated folders and artifacts.";
	@echo "clean-pyc              : Remove python artifacts."
	@echo "clean-build            : Remove build artifacts."
	@echo "install_requirements   : Install all the packages listed in *requirements*.txt files.";
	@echo "test                   : Run tests and generate coverage report.";
	@echo "upload_docs            : Upload built sphinx documentation.";

# Clean the folder from build/test related folders
clean: clean-build clean-pyc
	rm -rf .mypy_cache/
	rm -rf .pytest_cache/
	rm -f .coverage

clean-pyc:
	find . -name '*.pyc' -exec rm -rf {} +
	find . -name '*.pyo' -exec rm -rf {} +

clean-build:
	rm -rf build/
	rm -rf dist/
	rm -rf *.egg-info

# Install all the packages listed in *requirements*.txt files.
install_requirements:
	find . -name '*requirements*.txt' -exec python -m pip install -r {} \;

# Install requirements for testing and run tests
test: install_requirements
	pytest